---
Name: nswdpc-feedback-assist
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'NSWDPC\FeedbackAssist\Extensions\FASiteConfigExtension'

Page:
  extensions:
    - 'NSWDPC\FeedbackAssist\Extensions\FAPageExtension'

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - 'NSWDPC\FeedbackAssist\Extensions\FAContentControllerExtension'
